import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import Navbar from "@/components/custom/navbar";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SidebarProvider className="flex justify-start items-center">
        <Navbar />
        <body
          className={`${geistMono.variable} w-full antialiased`}
        >
          {children}
        </body>
      </SidebarProvider>
    </html>
  );
}